author: Minor Gordon
branding:
  icon: loader
description: Extract, transform, and load data from a Paradicms-formatted Airtable
  base.
inputs:
  airtable_access_token:
    description: Airtable access token (not API key), see https://support.airtable.com/docs/creating-and-using-api-keys-and-access-tokens
    required: true
  airtable_base_id:
    description: Airtable base id such as appgU92SdGTwPIVNg, see the base API documentation
    required: true
  cache_directory_path:
    default: .paradicms/.cache
    description: Path to a directory in which to store cached data
    required: false
  debug:
    description: Debug the action
    required: false
  loaded_data_directory_path:
    default: .paradicms/data
    description: Path to a directory in which to store the loaded RDF file
    required: false
  loaded_data_file_path:
    description: Path to a file in which to store the loaded RDF, overrides data_directory_path
      if specified
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
  profile:
    default: costume_core
    description: 'Application profile of the data/metadata in the Airtable metadata,
      one of: costume_core'
    required: false
name: Extract, transform, and load data from a Paradicms-formatted Airtable base.
runs:
  image: Dockerfile
  using: docker
